.env.example
.github/pull_request_template.md
app/utils/misc.ts
e2e/auth.json
e2e/base-test.ts
e2e/logout.spec.ts
playwright.config.ts

Make it easier for contributors to get started with the e2e tests.

test: improve e2e tests infrastructure

---

.markdownlintignore
CODE_OF_CONDUCT.md
LICENSE

Complete [pre-launch checklist](https://opensource.guide/starting-a-project/#your-pre-launch-checklist)

docs: complete pre-launch checklist

---

README.md

docs: add more badges to the README.md file

---

docs/diagrams.md
docs/diagrams/subscription-state.puml
docs/diagrams/transaction-state.puml

docs: add state diagrams

---

.clabot

ci: add .clabot file

---

.clabot
docs/diagrams/transaction-flow.puml

docs: rename `User` to `Member` in Transaction Flow diagram

---

package.json

Closes #47
Fix bug when run command `npm run setup`, but first time using `playwright`

fix: add pre-script for install deps playwright

---

.github/workflows/test.yml
README.md
package.json

to fix `package-lock.json` conflicts in #34 & #45

build: require node@16 & npm@8 to avoid `package-lock.json` mismatches

---

package-lock.json

Closes #67 
Upgrade `package-lock.json`
- node 16.13.1
- npm 8.1.2

ci: upgrade lockfileVersion to 2

---

.github/ISSUE_TEMPLATE/feature-request.md

to colocate the image previews and code snippets sections

docs: update feature-request issue template

---

CONTRIBUTING.md
CONTRIBUTING_ID.md

docs: explain GitHub Project views

---

app/models/enum.ts
docs/diagrams.md
docs/diagrams/consumption-state.puml
docs/diagrams/erd.puml

Also adding transaction method as suggested in https://github.com/zainfathoni/kelas.rumahberbagi.com/pull/45#discussion_r775190494

docs: add consumption table in the ERD

---

e2e/logout.spec.ts

to fix the failing e2e tests in @AchmadWahyu's local machine

fix: flaky e2e test in noscript browser

---

docs/diagrams/erd.puml

docs: update Transaction relationship

---

app/components/hero-section.tsx
app/components/logo.tsx
app/components/sections/pricing.tsx
app/root.tsx
app/routes/dashboard.tsx
app/routes/dashboard/index.tsx
app/routes/dashboard/profile/index.tsx
package-lock.json
package.json
tailwind.config.js

Closes #123
https://tailwindcss.com/docs/upgrade-guide

build: upgrade to Tailwind CSS v3

---

app/components/__tests__/step.test.tsx
app/components/breadcrumbs.tsx
app/components/button-link.tsx
app/components/logo.tsx
app/components/sections/pricing.tsx
app/routes/dashboard.tsx
app/routes/dashboard/index.tsx
app/routes/dashboard/purchase.tsx
app/routes/dashboard/purchase/completed.tsx
app/routes/dashboard/purchase/confirm.tsx
app/routes/dashboard/purchase/index.tsx
app/routes/dashboard/purchase/verify.tsx
app/routes/dashboard/transactions.tsx
app/routes/dashboard/transactions/$transactionId.tsx
app/utils/constants.ts

feat: implement Breadcrumbs

---

package.json

http://vercel.link/node-version
Closes

build: update NodeJS engine requirement to 14.x

---

app/components/alerts.tsx
app/entry.server.tsx
app/routes/login.tsx
e2e/fixtures/auth/public.json
e2e/login.spec.ts
package.json
playwright-global-setup.ts

build: fix Vercel deployment

---

app/components/form-elements.tsx
app/routes/dashboard/profile/edit.tsx

feat: add InputInstruction to add longer description for the Field

---

app/components/breadcrumbs.tsx
app/models/transaction.ts
app/routes/dashboard.tsx
app/routes/dashboard/purchase/confirm.tsx
app/routes/dashboard/transactions/$transactionId.tsx
app/routes/dashboard/transactions/$transactionId/$action.tsx

feat: optional datetime

---

app/root.tsx
app/routes/login.tsx
app/routes/magic.tsx
app/services/auth.server.ts
app/services/email.server.tsx
app/services/verifier.server.ts
package-lock.json
package.json

with a remix-auth-email-link authentication strategy
https://github.com/sergiodxa/remix-auth/discussions/111

refactor: use the latest version of remix-auth

---

app/routes/dashboard/transactions/$transactionId/$action.tsx

until we can increase the notes field size in the schema

fix: add maximum length to the notes field to avoid server error

---

app/routes/dashboard/profile/edit.tsx
app/utils/validators.ts

due to leading/trailing spaces

fix: trim the phoneNumber to avoid false negatives

---

app/services/session.server.ts

https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies

feat: set session cookie expiry into seven days
